version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mindlyfe-postgres
    environment:
      POSTGRES_DB: mindlyfe
      POSTGRES_USER: mindlyfe_user
      POSTGRES_PASSWORD: mindlyfe_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./POSTGRESQL_SCHEMA_MIGRATION.sql:/docker-entrypoint-initdb.d/02-migration.sql
    networks:
      - mindlyfe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mindlyfe_user -d mindlyfe"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mindlyfe-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mindlyfe
      DB_USER: mindlyfe_user
      DB_PASSWORD: mindlyfe_password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:8080
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mindlyfe-network
    volumes:
      - ./backend/src:/app/src
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindlyfe-frontend
    environment:
      VITE_API_URL: http://localhost:3001/api
      VITE_APP_NAME: Mindlyfe
      VITE_APP_VERSION: 1.0.0
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mindlyfe-network

volumes:
  postgres_data:
    driver: local

networks:
  mindlyfe-network:
    driver: bridge