
import {
  LayoutDashboard,
  Book,
  Calendar,
  MessageSquare,
  User,
  Users,
  Heart,
  HelpCircle,
  BarChart,
  Settings,
  FileText,
  Shield,
  AlarmClock,
  Activity,
  Lock,
  Search,
  Headphones,
  Video,
} from "lucide-react";

export const sidebarLinks = [
  { label: "Dashboard", path: "/dashboard", icon: LayoutDashboard },
  { label: "Assessment", path: "/assessment", icon: FileText },
  { label: "Progress Tracking", path: "/progress", icon: BarChart },
  { label: "Therapist Matching", path: "/therapist-matching", icon: Users },
  { label: "Therapy Sessions", path: "/sessions", icon: Calendar },
  { label: "Resources", path: "/resources", icon: Book },
  { label: "Self-Help Tools", path: "/tools", icon: Heart },
  { label: "Community", path: "/community", icon: MessageSquare },
  { label: "Wellness Programs", path: "/wellness", icon: Heart },
  { label: "Crisis Support", path: "/crisis", icon: HelpCircle },
  { label: "Lifestyle Management", path: "/lifestyle", icon: User },
  { label: "AI Assistant", path: "/ai-assistant", icon: Activity },
  { label: "Personalization", path: "/personalization", icon: Settings },
  { label: "Gamification", path: "/gamification", icon: BarChart },
  { label: "Admin Dashboard", path: "/admin", icon: Shield },
  // Add more links here as needed for each major feature
];
